config/routes.rb
Donation::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  resources :categories

  devise_for :admins
  devise_for :users
  resources :products
  root to: 'home#index'

  resources :users, :path => '', :only => [:show]
  post "users/create_request", to: "users#create_request", as: "create_request"
  get "users/destroy_request", to: "users#destroy_request", as: "destroy_request"
  post "users/create_contribute", to: "users#create_contribute", as: "create_contribute"
  get "users/destroy_contribute", to: "users#destroy_contribute", as: "destroy_contribute"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    else
      # Not familiar enough with the app, so I'm restricting
      # non-admin users to just have read access --Edmund 1/18/2014
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/donor.rb
class Donor < User
  default_scope { includes(:roles).where(roles: {name: 'donor'}) }

  has_many :donor_product_relations, foreign_key: 'user_id'
  has_many :products, through: :donor_product_relations

  after_create :set_donor_role

  private

    def set_donor_role
      self.roles << Role.find_or_create_by(name: 'donor')
    end
end

app/models/donor_product_relation.rb
class DonorProductRelation < ActiveRecord::Base
  belongs_to :donor, foreign_key: 'user_id'
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :donor_product_relations
  has_many :donors, through: :donor_product_relations
  has_many :requester_product_relations
  has_many :requesters, through: :requester_product_relations

  def sum_needed_amount
    requester_product_relations.inject(0){|sum, request| sum += request.amount}
  end

  def sum_current_amount
    donor_product_relations.inject(0){|sum, donation| sum += donation.amount}
  end

  def percent
    percent = if sum_needed_amount == 0
                0
              else
               (sum_current_amount.to_f / sum_needed_amount.to_f) * 100
              end
    percent.round(2)
  end

  def self.food
    @food ||= Product.find_by(name: "Food")
  end

  def self.water
    @water ||= Product.find_by(name: "Water")
  end

  def self.firstaid
    @firstaid ||= Product.find_by(name: "First Aid")
  end

  def self.clothes
    @clothes ||= Product.find_by(name: "Clothes")
  end
end

app/models/requester.rb
class Requester < User
  default_scope { includes(:roles).where(roles: {name: 'requester'}) }

  has_many :requester_product_relations, foreign_key: 'user_id'
  has_many :products, through: :requester_product_relations

  after_create :set_requester_role

  private

    def set_requester_role
      self.roles << Role.find_or_create_by(name: 'requester')
    end
end

app/models/requester_product_relation.rb
class RequesterProductRelation < ActiveRecord::Base
  belongs_to :requester, foreign_key: 'user_id'
  belongs_to :product
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  geocoded_by :address
  after_validation :geocode

  def requester?
    type == "Requester"
  end

  def donor?
    type == "Donor"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name << :address << :type << :avatar << :description
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @requesters = Requester.all
    @hash = ''
    @requesters.each do |requester|
      @hash += '[' + requester.latitude.to_s + ', ' + requester.longitude.to_s + ', "' + requester.name + '"],'
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
#  before_action :authenticate_donor!, only: [:show]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :amount)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])
    case @user.type
    when "Requester"
      @requests = @user.requester_product_relations
    when "Donor"
      @contributes = @user.donor_product_relations
    end
  end

  def create_request
    @user = User.find(params[:request][:requester_id])
    @user.requester_product_relations.create(product_id: params[:request][:product_id], amount: params[:request][:amount])
    redirect_to user_path(@user)
  end

  def destroy_request
    @user = User.find(params[:requester_id])
    @user.requester_product_relations.destroy(params[:id])
    redirect_to user_path(@user)
  end

  def create_contribute
    @user = User.find(params[:contribute][:donor_id])
    @user.donor_product_relations.create(product_id: params[:contribute][:product_id], amount: params[:contribute][:amount])
    redirect_to user_path(@user)
  end

  def destroy_contribute
    @user = User.find(params[:donor_id])
    @user.donor_product_relations.destroy(params[:id])
    redirect_to user_path(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<div class="jumbotron">
  <div id="map"></div>
</div>

<div class="container">
  <div class="row" id="category">
    <div class="col-md-3" id="food"><%= link_to "FOOD", Product.food %></div>
    <div class="col-md-3" id="water"><%= link_to "WATER", Product.water %></div>
    <div class="col-md-3" id="first_aid"><%= link_to "FIRST AID", Product.firstaid %></div>
    <div class="col-md-3" id="clothes"><%= link_to "CLOTHES", Product.clothes %></div>
  </div>
</div>

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
  google.load("visualization", "1", {packages:["map"]});
  google.setOnLoadCallback(drawMap);
  function drawMap() {
    var data = google.visualization.arrayToDataTable([
      ['Lat', 'Lon', 'Name'],
      <%= raw @hash %>
    ]);
 
    var map = new google.visualization.Map(document.getElementById('map'));
    map.draw(data, {showTip: true});
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Donation</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" />
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.min.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div id='wrap'>
      <header id="header">
        <%= render "shared/menu" %>
      </header>

      <div id='main'>
        <%= render :partial => 'shared/flash', :locals => {:flash => flash} %>
        <%= yield %>
      </div>
    </div>

    <footer id='footer'>
      <div class="container">
        <p class="text-muted">&copy; 2014 Built for Angelhack NYC.</p>
      </div>
    </footer>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Amount</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.amount %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <h1><img src="<%= @product.image_url%>" title="  <%= @product.name %> " width="200">   <%= @product.name %> </h1>
      </div>
      <div class="col-lg-8">
        <div class="progress progress-striped active">
          <%- percent = @product.percent%>
          <div class="progress-bar " role="progressbar" aria-valuenow=<%=percent%> aria-valuemin="0" aria-valuemax="100" style='<%="width: #{percent}%"%>'>
            <span class="sr-only"><%=percent%>% Complete</span>
          </div>
        </div>
        <h2>Status: <%=percent%>% needs met </h2>
      </div>
    </div><!--row-->
  </div><!--container-->

  <div class="container">
    <div class="row">
        <div class="col-lg-6">
          <div id='donors'>
            <%= render 'shared/donors', product: @product %>
          </div>
        </div>
        <div class="col-lg-6">
          <div id='requester'>
            <%= render 'shared/requester', product: @product %>
          </div>
       </div>
    </div><!--row-->
  </div><!--container-->

app/views/shared/_donors.html.erb
<h3> List of Suppliers </h3>

<ul class="list-unstyled">
  <%- product.donor_product_relations.each do |donation| %>
    <li class="name clearfix">
      <span class="user-info pull-left">
        <span><img style='width: 60px; height: 60px; padding-right: 10px;' src=<%=donation.donor.try(:avatar_url)%>>
          <span class="h3"><%= donation.donor.try(:name) %> </span>
        </span>
        <%= donation.donor.try(:address) %>
      </span>
      <span class="time pull-right">
        <span class="uppercase h3 timestamp"><%= donation.status%> </span> <br />
        <span class="ago"><%= time_ago_in_words donation.created_at%> ago </span>
        <br />
        <span class="box">  <%= donation.amount%> meals given</span>
      </span>
    </li>
  <% end %>
</ul>

app/views/shared/_flash.html.erb
<div class='flash-bar'>
  <% if flash.notice %>
    <div class="alert alert-success alert-dismissable">
      <%#<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>%>
      <%= flash[:notice] %>
    </div>
  <% elsif flash.alert %>
    <div class="alert alert-danger alert-dismissable">
      <%#<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>%>
      <%= flash[:alert] %>
    </div>
  <% end %>
</div>

app/views/shared/_menu.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Relief Insight", root_path, class: "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav user-bar pull-right">
        <%- if current_user -%>
          <li><%= link_to "DASHBOARD", user_path(current_user.id) %></li>
          <li><%= link_to "ACCOUNT SETTINGS", edit_user_registration_path %></li>
          <li><%= link_to "LOGOUT", destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li>
            <%= link_to "REGISTER", new_user_registration_path %>
          </li>
          <li>
            <%= link_to "LOGIN", new_user_session_path %>
          </li>
        <%- end -%>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_requester.html.erb
<h3> List of Receivers</h3>

<ul class="list-unstyled">
  <%- product.requester_product_relations.each do |request| %>
    <li class="name clearfix">
      <span class="user-info pull-left">
        <span>
          <img style='width: 60px; height: 60px;' src=<%=request.try(:requester).try(:avatar_url)%>>
          <span class="h3"> <%= request.try(:requester).try(:name) %></span>
        </span>
        <span><%= request.try(:requester).try(:address) %> </span>
      </span>

      <span class="time pull-right">
        <span class="uppercase h3 timestamp"><%= request.status%></span> <br />
        <span class="ago"><%= time_ago_in_words request.created_at%> ago </span>
        <br />
        <span class="box"><%= request.amount%> meals requested</span>
      </span>
    </li>
  <% end %>
</ul>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div>
  <div>
    <h2>User's information</h2>
    name: <%= @user.name %>
    <br/>
    <%= image_tag @user.avatar_url %>
    <br/>
    address: <%= @user.address %>
    <br/>
    latitude: <%= @user.latitude %>
    <br>
    longitude: <%= @user.longitude  %>
  </div>
</div>

<% if @user.requester? and @requests %>
  <% unless @requests.blank? %>
  <div class="container">
    <table class="table">
      <thead>
        <tr>
         <th>product</th>
         <th>requester</th>
         <th>amount</th>
         <th>status</th>
         <th></th>
        </tr>
      </thead>
      <tbody>
        <% @requests.each do |request| %>
          <tr>
            <td><%= request.try(:product).try(:name) %></td>
            <td><%= request.try(:requester).try(:name) %></td>
            <td><%= request.amount %></td>
            <td><%= request.status %></td>
            <td>
              <%= link_to "destroy", destroy_request_path(id: request.id, requester_id:@user.id) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <% end %>

  <%= simple_form_for RequesterProductRelation.new, as: :request, url: create_request_path, :html => { :class => 'form-horizontal' } do |f| %>
    <%= f.hidden_field :requester_id , value: @user.id %>
    <%= f.input :product_id, collection: Product.all %>
    <%= f.input :amount %>
    <div class="form-actions">
      <%= f.button :submit, :class => 'btn-primary' %>
    </div>
  <% end %>
<% end %>

<% if @user.donor? and @contributes %>
  <% unless @contributes.blank? %>
  <div class="container">
    <table class="table">
      <thead>
        <tr>
         <th>product</th>
         <th>contributor</th>
         <th>amount</th>
         <th>status</th>
         <th>action</th>
        </tr>
      </thead>
      <tbody>
        <% @contributes.each do |contribute| %>
          <tr>
            <td><%= contribute.try(:product).try(:name) %></td>
            <td><%= contribute.try(:donor).try(:name) %></td>
            <td><%= contribute.amount %></td>
            <td><%= contribute.status %></td>
            <td>
              <%= link_to "destroy", destroy_contribute_path(id: contribute.id, donor_id:@user.id) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <% end %>

  <%= simple_form_for DonorProductRelation.new, as: :contribute, url: create_contribute_path, :html => { :class => 'form-horizontal' } do |f| %>
    <%= f.hidden_field :donor_id, value: @user.id %>
    <%= f.input :product_id, collection: Product.all %>
    <%= f.input :amount %>
    <div class="form-actions">
      <%= f.button :submit, :class => 'btn-primary' %>
    </div>
  <% end %>
<% end %>